"""Add agent_ids to tasks table

Revision ID: 0003_add_agent_ids_to_tasks
Revises: 0002_add_nodes_table
Create Date: 2025-07-30 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_add_agent_ids_to_tasks'
down_revision: Union[str, None] = '0002_add_nodes_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('agent_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'agent_ids')
    # ### end Alembic commands ###