"""add agent_ids to tasks

Revision ID: 0003
Revises: 0002
Create Date: 2025-08-10 21:37:38.800757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_add_agent_ids_to_tasks'
down_revision = '0002_add_nodes_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('agent_ids')

    # ### end Alembic commands ###