"""merge heads

Revision ID: 0009_merge_heads
Revises: 0008_add_reports_tables, 3c6bef228603
Create Date: 2025-01-21 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0009_merge_heads'
down_revision: Union[str, Sequence[str], None] = ('0008_add_reports_tables', '3c6bef228603')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a merge migration, no changes needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a merge migration, no changes needed
    pass
    # ### end Alembic commands ###