const pinyinToChinese = {
  'beijing': '北京市',
  'tianjin': '天津市',
  'shanghai': '上海市',
  'chongqing': '重庆市',
  'hebei': '河北省',
  'henan': '河南省',
  'yunnan': '云南省',
  'liaoning': '辽宁省',
  'heilongjiang': '黑龙江省',
  'hunan': '湖南省',
  'anhui': '安徽省',
  'shandong': '山东省',
  'xinjiang': '新疆维吾尔自治区',
  'jiangsu': '江苏省',
  'zhejiang': '浙江省',
  'jiangxi': '江西省',
  'hubei': '湖北省',
  'guangxi': '广西壮族自治区',
  'gansu': '甘肃省',
  'shanxi': '山西省',
  'neimenggu': '内蒙古自治区',
  'shaanxi': '陕西省',
  'jilin': '吉林省',
  'fujian': '福建省',
  'guizhou': '贵州省',
  'guangdong': '广东省',
  'guangzhou': '广州市',
  'qinghai': '青海省',
  'xizang': '西藏自治区',
  'sichuan': '四川省',
  'ningxia': '宁夏回族自治区',
  'hainan': '海南省',
  'taiwan': '台湾省',
  'xianggang': '香港特别行政区',
  'aomen': '澳门特别行政区'
}

export default pinyinToChinese